// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_web']!,
    appId: '1:840509322802:web:59d589aa38d556d6b86e2b',
    messagingSenderId: '840509322802',
    projectId: 'blog-app-76ae1',
    authDomain: 'blog-app-76ae1.firebaseapp.com',
    storageBucket: 'blog-app-76ae1.firebasestorage.app',
    measurementId: 'G-C97ZGYJJR0',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_android']!,
    appId: '1:840509322802:android:e61a951074120ff9b86e2b',
    messagingSenderId: '840509322802',
    projectId: 'blog-app-76ae1',
    storageBucket: 'blog-app-76ae1.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_ios']!,
    appId: '1:840509322802:ios:06ec9e87b6cff91ab86e2b',
    messagingSenderId: '840509322802',
    projectId: 'blog-app-76ae1',
    storageBucket: 'blog-app-76ae1.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_macos']!,
    appId: '1:840509322802:ios:06ec9e87b6cff91ab86e2b',
    messagingSenderId: '840509322802',
    projectId: 'blog-app-76ae1',
    storageBucket: 'blog-app-76ae1.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_windows']!,
    appId: '1:840509322802:web:741bcaa5caaf3aa8b86e2b',
    messagingSenderId: '840509322802',
    projectId: 'blog-app-76ae1',
    authDomain: 'blog-app-76ae1.firebaseapp.com',
    storageBucket: 'blog-app-76ae1.firebasestorage.app',
    measurementId: 'G-G4ZB8M6V2M',
  );
}
